### PR TITLE
Adds Longhorn v1.6.2 integration test

### PR DESCRIPTION
**Pull request by claudiubelu**
We have already added rocks for Longhorn v1.6.2. We should test them as well.

### CODE REVIEW

**Review by bschimke95 — COMMENTED** [review]
looks good in general but seems like the tests are failing

**Comment by claudiubelu** [comment]
> looks good in general but seems like the tests are failing

Because the fix needs to be merged first: https://github.com/canonical/longhorn-rocks/pull/26

**Comment by bschimke95** [comment]
alright, merged the other PR
Please rebase/rerun the tests and then we can merge.

**Review by bschimke95 — APPROVED** [review]
LGTM

**Pull request merged**
